version: '3.8'

services:
  spring:
    container_name: javaspringboot
    image: rafaelportomoura/javaspringboot:latest
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - back.env
      - db.env
    networks:
      - data

  db:
    container_name: postgresdb
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    env_file: db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - data

  adminer-db:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - data

volumes:
  postgres-data:

networks:
  data:
