version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: javadev
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    env_file:
      - back.env
      - db.env

    volumes:
      - ../:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
